### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by matthiasdiener** [inducer/dagrt#11]
Most recent version on pypi is 2014.1 (https://pypi.org/project/dagrt/#history), while (e.g.) mirgecom requires >=2019.1 (https://github.com/illinois-ceesd/mirgecom/blob/46243dccda50b044630408d90cb5ea48e67a283d/setup.py#L56).

**Comment by inducer** [comment]
- https://pypi.org/project/dagrt/2021.1/
- https://pypi.org/project/leap/2021.1/
